### ISSUE TITLE
Can this be added after installation?

### ISSUE THREAD

**Issue by mbrost** [ansible/awx-logos#1]
I completed the installation (docker method) and started to develop AWX and just later realized there was this option.

Is it possible to apply this after installation? I tried to reinstall with the 'awx_offical=true' and its still showing the angry potato man. 

I'd like to avoid completely removing AWX and starting over.

**Comment by wenottingham** [comment]
If you need to change it after release, post a custom logo under settings/Tower configuration.

**Comment by alizsyed** [comment]
This only changes the login page's logo. The dashboard still contains the angry potato in the top left corner after making this change, just fyi
